[2024-04-06T09:36:46.837+0000] {processor.py:153} INFO - Started process (PID=47) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:36:46.838+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:36:46.839+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:36:46.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:36:46.857+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:36:46.855+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:36:46.857+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:36:46.883+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.049 seconds
[2024-04-06T09:37:17.350+0000] {processor.py:153} INFO - Started process (PID=126) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:37:17.351+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:37:17.352+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:37:17.352+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:37:17.357+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:37:17.356+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:37:17.357+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:37:17.375+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.030 seconds
[2024-04-06T09:37:47.703+0000] {processor.py:153} INFO - Started process (PID=198) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:37:47.704+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:37:47.706+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:37:47.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:37:47.729+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:37:47.726+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:37:47.730+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:37:47.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.079 seconds
[2024-04-06T09:38:18.674+0000] {processor.py:153} INFO - Started process (PID=286) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:38:18.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:38:18.675+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:38:18.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:38:18.689+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:38:18.688+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:38:18.690+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:38:18.717+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.048 seconds
[2024-04-06T09:38:49.305+0000] {processor.py:153} INFO - Started process (PID=357) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:38:49.312+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:38:49.313+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:38:49.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:38:49.318+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:38:49.317+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:38:49.318+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:38:49.334+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.032 seconds
[2024-04-06T09:39:19.434+0000] {processor.py:153} INFO - Started process (PID=446) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:39:19.440+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:39:19.441+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:39:19.440+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:39:19.447+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:39:19.446+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:39:19.447+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:39:19.466+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.035 seconds
[2024-04-06T09:39:49.694+0000] {processor.py:153} INFO - Started process (PID=517) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:39:49.700+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:39:49.701+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:39:49.701+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:39:49.706+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:39:49.705+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:39:49.706+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:39:49.723+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.031 seconds
[2024-04-06T09:40:19.884+0000] {processor.py:153} INFO - Started process (PID=605) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:40:19.890+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:40:19.892+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:40:19.891+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:40:19.900+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:40:19.898+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:40:19.900+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:40:19.925+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.044 seconds
[2024-04-06T09:40:50.289+0000] {processor.py:153} INFO - Started process (PID=677) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:40:50.295+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:40:50.296+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:40:50.296+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:40:50.305+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:40:50.304+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:40:50.306+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:40:50.330+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.044 seconds
[2024-04-06T09:41:20.560+0000] {processor.py:153} INFO - Started process (PID=765) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:41:20.572+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:41:20.573+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:41:20.573+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:41:20.594+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:41:20.593+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:41:20.594+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:41:20.629+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.072 seconds
[2024-04-06T09:41:51.155+0000] {processor.py:153} INFO - Started process (PID=837) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:41:51.161+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:41:51.161+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:41:51.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:41:51.166+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:41:51.165+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:41:51.166+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:41:51.184+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.031 seconds
[2024-04-06T09:42:21.349+0000] {processor.py:153} INFO - Started process (PID=918) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:42:21.355+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:42:21.356+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:42:21.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:42:21.362+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:42:21.361+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:42:21.362+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:42:21.386+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.039 seconds
[2024-04-06T09:42:52.157+0000] {processor.py:153} INFO - Started process (PID=997) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:42:52.158+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:42:52.158+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:42:52.158+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:42:52.163+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:42:52.163+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:42:52.164+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:42:52.180+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.026 seconds
[2024-04-06T09:43:22.259+0000] {processor.py:153} INFO - Started process (PID=1077) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:43:22.265+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:43:22.265+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:43:22.265+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:43:22.273+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:43:22.271+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:43:22.273+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:43:22.300+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.045 seconds
[2024-04-06T09:43:52.935+0000] {processor.py:153} INFO - Started process (PID=1156) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:43:52.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:43:52.941+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:43:52.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:43:52.946+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:43:52.945+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:43:52.946+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:43:52.962+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.029 seconds
[2024-04-06T09:44:23.212+0000] {processor.py:153} INFO - Started process (PID=1228) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:44:23.213+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:44:23.214+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:44:23.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:44:23.220+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:44:23.219+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:44:23.220+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:44:23.242+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.033 seconds
[2024-04-06T09:44:53.996+0000] {processor.py:153} INFO - Started process (PID=1316) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:44:54.001+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:44:54.002+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:44:54.002+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:44:54.007+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:44:54.006+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:44:54.007+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:44:54.023+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.030 seconds
[2024-04-06T09:45:24.297+0000] {processor.py:153} INFO - Started process (PID=1388) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:45:24.303+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:45:24.303+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:45:24.303+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:45:24.309+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:45:24.308+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:45:24.309+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:45:24.326+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.033 seconds
[2024-04-06T09:45:54.569+0000] {processor.py:153} INFO - Started process (PID=1476) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:45:54.570+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:45:54.571+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:45:54.570+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:45:54.577+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:45:54.576+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:45:54.577+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:45:54.596+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.031 seconds
[2024-04-06T09:46:25.087+0000] {processor.py:153} INFO - Started process (PID=1547) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:46:25.092+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:46:25.093+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:46:25.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:46:25.098+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:46:25.097+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:46:25.098+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:46:25.115+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.030 seconds
[2024-04-06T09:46:55.484+0000] {processor.py:153} INFO - Started process (PID=1635) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:46:55.491+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:46:55.492+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:46:55.492+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:46:55.497+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:46:55.496+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:46:55.498+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:46:55.514+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.034 seconds
[2024-04-06T09:47:25.876+0000] {processor.py:153} INFO - Started process (PID=1706) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:47:25.881+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:47:25.882+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:47:25.882+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:47:25.887+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:47:25.886+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:47:25.887+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:47:25.903+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.032 seconds
[2024-04-06T09:47:56.277+0000] {processor.py:153} INFO - Started process (PID=1795) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:47:56.278+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:47:56.278+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:47:56.278+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:47:56.283+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:47:56.283+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:47:56.284+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:47:56.300+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.025 seconds
[2024-04-06T09:48:26.427+0000] {processor.py:153} INFO - Started process (PID=1867) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:48:26.433+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:48:26.433+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:48:26.433+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:48:26.438+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:48:26.438+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:48:26.439+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:48:26.455+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.032 seconds
[2024-04-06T09:48:57.062+0000] {processor.py:153} INFO - Started process (PID=1955) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:48:57.063+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:48:57.064+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:48:57.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:48:57.072+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:48:57.070+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:48:57.072+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:48:57.092+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.034 seconds
[2024-04-06T09:49:33.837+0000] {processor.py:153} INFO - Started process (PID=2011) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:49:34.006+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:49:37.257+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:49:35.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:50:11.759+0000] {processor.py:153} INFO - Started process (PID=37) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:50:11.760+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:50:11.760+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:50:11.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:50:11.767+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:50:11.765+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:50:11.767+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:50:11.785+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.029 seconds
[2024-04-06T09:50:42.896+0000] {processor.py:153} INFO - Started process (PID=109) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:50:42.898+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:50:42.899+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:50:42.899+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:50:42.934+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:50:42.929+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:50:42.935+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:50:43.008+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.166 seconds
[2024-04-06T09:51:13.967+0000] {processor.py:153} INFO - Started process (PID=191) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:51:13.968+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:51:13.968+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:51:13.968+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:51:13.974+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:51:13.973+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:51:13.974+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:51:13.992+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.027 seconds
[2024-04-06T09:58:23.000+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:58:23.001+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:58:23.002+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:58:23.002+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:58:23.019+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:58:23.018+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:58:23.020+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:58:23.044+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.048 seconds
[2024-04-06T09:58:53.445+0000] {processor.py:153} INFO - Started process (PID=126) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:58:53.446+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:58:53.447+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:58:53.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:58:53.457+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:58:53.456+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:58:53.457+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:58:53.479+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.037 seconds
[2024-04-06T09:59:24.000+0000] {processor.py:153} INFO - Started process (PID=199) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:59:24.020+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:59:24.021+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:59:24.021+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:59:24.026+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:59:24.025+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:59:24.026+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:59:24.069+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.071 seconds
[2024-04-06T09:59:54.420+0000] {processor.py:153} INFO - Started process (PID=270) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:59:54.422+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T09:59:54.424+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:59:54.423+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:59:54.433+0000] {logging_mixin.py:137} INFO - [2024-04-06T09:59:54.432+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T09:59:54.433+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T09:59:54.453+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.037 seconds
[2024-04-06T10:00:25.033+0000] {processor.py:153} INFO - Started process (PID=342) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:00:25.034+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:00:25.035+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:00:25.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:00:25.044+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:00:25.042+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:00:25.044+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:00:25.062+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.033 seconds
[2024-04-06T10:00:55.109+0000] {processor.py:153} INFO - Started process (PID=414) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:00:55.109+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:00:55.110+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:00:55.110+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:00:55.116+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:00:55.115+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:00:55.116+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:00:55.132+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.026 seconds
[2024-04-06T10:01:25.477+0000] {processor.py:153} INFO - Started process (PID=502) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:01:25.483+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:01:25.483+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:01:25.483+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:01:25.487+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:01:25.487+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:01:25.488+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:01:25.502+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.029 seconds
[2024-04-06T10:01:55.835+0000] {processor.py:153} INFO - Started process (PID=590) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:01:55.835+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:01:55.836+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:01:55.836+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:01:55.841+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:01:55.841+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:01:55.842+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:01:55.857+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.025 seconds
[2024-04-06T10:02:26.239+0000] {processor.py:153} INFO - Started process (PID=662) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:02:26.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:02:26.245+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:02:26.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:02:26.249+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:02:26.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:02:26.249+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:02:26.264+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.028 seconds
[2024-04-06T10:02:56.896+0000] {processor.py:153} INFO - Started process (PID=750) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:02:56.896+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:02:56.897+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:02:56.897+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:02:56.902+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:02:56.901+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:02:56.902+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:02:56.917+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.024 seconds
[2024-04-06T10:03:27.358+0000] {processor.py:153} INFO - Started process (PID=823) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:03:27.360+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:03:27.361+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:03:27.360+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:03:27.369+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:03:27.368+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:03:27.370+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:03:27.398+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.042 seconds
[2024-04-06T10:03:57.633+0000] {processor.py:153} INFO - Started process (PID=910) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:03:57.633+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:03:57.634+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:03:57.634+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:03:57.639+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:03:57.638+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:03:57.639+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:03:57.656+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.025 seconds
[2024-04-06T10:04:28.408+0000] {processor.py:153} INFO - Started process (PID=982) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:04:28.414+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:04:28.414+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:04:28.414+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:04:28.419+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:04:28.419+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:04:28.419+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:04:28.435+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.029 seconds
[2024-04-06T10:04:59.009+0000] {processor.py:153} INFO - Started process (PID=1070) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:04:59.010+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:04:59.010+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:04:59.010+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:04:59.016+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:04:59.015+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:04:59.016+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:04:59.032+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.027 seconds
[2024-04-06T10:05:29.927+0000] {processor.py:153} INFO - Started process (PID=1142) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:05:29.928+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:05:29.929+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:05:29.928+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:05:29.934+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:05:29.934+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:05:29.935+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:05:29.954+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.030 seconds
[2024-04-06T10:06:00.714+0000] {processor.py:153} INFO - Started process (PID=1230) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:06:00.715+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:06:00.717+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:06:00.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:06:00.726+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:06:00.725+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:06:00.727+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:06:00.758+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.050 seconds
[2024-04-06T10:06:30.987+0000] {processor.py:153} INFO - Started process (PID=1303) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:06:30.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:06:30.990+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:06:30.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:06:31.000+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:06:30.998+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:06:31.001+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:06:31.034+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.053 seconds
[2024-04-06T10:07:01.674+0000] {processor.py:153} INFO - Started process (PID=1374) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:07:01.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:07:01.682+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:07:01.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:07:01.692+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:07:01.691+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:07:01.693+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:07:01.725+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.057 seconds
[2024-04-06T10:07:31.978+0000] {processor.py:153} INFO - Started process (PID=1446) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:07:31.979+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:07:31.981+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:07:31.980+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:07:31.991+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:07:31.989+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:07:31.991+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:07:32.026+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.053 seconds
[2024-04-06T10:08:02.094+0000] {processor.py:153} INFO - Started process (PID=1518) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:08:02.101+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:08:02.102+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:08:02.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:08:02.113+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:08:02.112+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:08:02.114+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:08:02.149+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.060 seconds
[2024-04-06T10:08:32.611+0000] {processor.py:153} INFO - Started process (PID=1590) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:08:32.613+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:08:32.614+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:08:32.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:08:32.627+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:08:32.625+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:08:32.628+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:08:32.660+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.055 seconds
[2024-04-06T10:09:03.399+0000] {processor.py:153} INFO - Started process (PID=1662) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:09:03.401+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:09:03.403+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:09:03.403+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:09:03.435+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:09:03.433+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:09:03.436+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:09:03.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.093 seconds
[2024-04-06T10:09:34.014+0000] {processor.py:153} INFO - Started process (PID=1735) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:09:34.020+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:09:34.021+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:09:34.021+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:09:34.032+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:09:34.030+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:09:34.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:09:34.063+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.054 seconds
[2024-04-06T10:10:04.114+0000] {processor.py:153} INFO - Started process (PID=1806) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:10:04.120+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:10:04.121+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:10:04.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:10:04.130+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:10:04.129+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:10:04.131+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:10:04.163+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.055 seconds
[2024-04-06T10:10:34.563+0000] {processor.py:153} INFO - Started process (PID=1887) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:10:34.565+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:10:34.566+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:10:34.566+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:10:34.577+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:10:34.575+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:10:34.577+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:10:34.612+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.054 seconds
[2024-04-06T10:11:04.813+0000] {processor.py:153} INFO - Started process (PID=1966) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:11:04.819+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:11:04.820+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:11:04.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:11:04.830+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:11:04.828+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:11:04.830+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:11:04.864+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.057 seconds
[2024-04-06T10:11:35.402+0000] {processor.py:153} INFO - Started process (PID=2038) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:11:35.403+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:11:35.405+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:11:35.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:11:35.417+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:11:35.415+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:11:35.418+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:11:35.456+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.062 seconds
[2024-04-06T10:12:05.943+0000] {processor.py:153} INFO - Started process (PID=2110) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:12:05.950+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:12:05.951+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:12:05.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:12:05.961+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:12:05.959+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:12:05.961+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:12:05.992+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.054 seconds
[2024-04-06T10:12:36.580+0000] {processor.py:153} INFO - Started process (PID=2182) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:12:36.581+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:12:36.582+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:12:36.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:12:36.593+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:12:36.591+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:12:36.594+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:12:36.627+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.054 seconds
[2024-04-06T10:13:07.353+0000] {processor.py:153} INFO - Started process (PID=2254) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:13:07.359+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:13:07.362+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:13:07.361+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:13:07.374+0000] {logging_mixin.py:137} INFO - [2024-04-06T10:13:07.371+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2024-04-06T10:13:07.374+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:13:07.410+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.063 seconds
[2024-04-06T10:42:02.125+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:42:02.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:42:02.127+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:42:02.126+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:42:02.144+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:42:02.142+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-04-06T10:42:02.144+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:42:02.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.040 seconds
[2024-04-06T10:42:32.473+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:42:32.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:42:32.476+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:42:32.476+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:42:32.485+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:42:32.484+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-04-06T10:42:32.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:42:32.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.031 seconds
[2024-04-06T10:43:02.634+0000] {processor.py:161} INFO - Started process (PID=146) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:43:02.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:43:02.636+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:43:02.636+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:43:02.653+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:43:02.652+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-04-06T10:43:02.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:43:02.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.034 seconds
[2024-04-06T10:43:33.325+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:43:33.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:43:33.331+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:43:33.331+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:43:33.336+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:43:33.335+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-04-06T10:43:33.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:43:33.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.028 seconds
[2024-04-06T10:44:03.967+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:44:03.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:44:03.969+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:44:03.969+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:44:03.979+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:44:03.978+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-04-06T10:44:03.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:44:03.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.028 seconds
[2024-04-06T10:44:34.706+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:44:34.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:44:34.710+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:44:34.709+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:44:34.725+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:44:34.724+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-04-06T10:44:34.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:44:34.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.036 seconds
[2024-04-06T10:45:04.830+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:45:04.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/model_pipeline.py for tasks to queue
[2024-04-06T10:45:04.837+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:45:04.837+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:45:04.842+0000] {logging_mixin.py:188} INFO - [2024-04-06T10:45:04.841+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/model_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_pipeline.py", line 5, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-04-06T10:45:04.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/model_pipeline.py
[2024-04-06T10:45:04.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/model_pipeline.py took 0.024 seconds
